# Sprint 6 – Data Preprocessing

## Objective

The objective of this sprint is to convert raw business data into a machine learning-ready format.

Machine learning algorithms cannot directly understand categorical values such as "Manual" or "Petrol". Therefore, preprocessing techniques like encoding and scaling are required.

In this sprint, we will build a reusable preprocessing pipeline using Scikit-learn.

In [2]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import ( StandardScaler , OneHotEncoder)

from sklearn.compose import ColumnTransformer 

from sklearn.pipeline import Pipeline 

import joblib

In [3]:
df = pd.read_csv("../data/interim/featured_ford.csv")
df.head()

     model  year  price  ... fuel_efficiency  tax_category price_segment
0   Fiesta  2017  12000  ...          medium        medium       Premium
1    Focus  2018  14000  ...          medium        medium       Premium
2    Focus  2017  13000  ...          medium        medium       Premium
3   Fiesta  2019  17500  ...          medium        medium        Luxury
4   Fiesta  2019  16500  ...          medium        medium        Luxury

[5 rows x 15 columns]

In [4]:
df = df.drop(columns=["price_segment"])
df.head()

     model  year  price  ... engine_category  fuel_efficiency tax_category
0   Fiesta  2017  12000  ...           small           medium       medium
1    Focus  2018  14000  ...           small           medium       medium
2    Focus  2017  13000  ...           small           medium       medium
3   Fiesta  2019  17500  ...          medium           medium       medium
4   Fiesta  2019  16500  ...           small           medium       medium

[5 rows x 14 columns]

In [5]:
X = df.drop(columns=["price"])

y = df["price"]

In [6]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
numerical_columns = X_train.select_dtypes(
    include = np.number 
).columns

categorical_columns = X_train.select_dtypes(
    exclude = np.number 
).columns

print(numerical_columns)

print(categorical_columns)

Index(['year', 'mileage', 'tax', 'mpg', 'engineSize', 'car_age',
       'mileage_per_year'],
      dtype='str')
Index(['model', 'transmission', 'fuelType', 'engine_category',
       'fuel_efficiency', 'tax_category'],
      dtype='str')

In [14]:
numerical_transformer  = StandardScaler()

In [15]:
categorical_transformer = OneHotEncoder(
    handle_unknown = "ignore"
)

In [17]:
preprocessor = ColumnTransformer(
    transformers =[
        ("num", numerical_transformer , numerical_columns),
        ("cat", categorical_transformer , categorical_columns)
    ]
)

In [19]:
X_train_processed  = preprocessor.fit_transform(
    X_train
)

In [21]:
X_test_processed = preprocessor.transform(X_test)

In [25]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(14372, 48)
(3594, 48)

In [27]:
joblib.dump(
    preprocessor,
    "../models/preprocessor.pkl"
)

['../models/preprocessor.pkl']

In [28]:
loaded_preprocessor= joblib.load(
    "../models/preprocessor.pkl"
)

In [29]:
print(loaded_preprocessor )

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['year', 'mileage', 'tax', 'mpg', 'engineSize', 'car_age',
       'mileage_per_year'],
      dtype='str')),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 Index(['model', 'transmission', 'fuelType', 'engine_category',
       'fuel_efficiency', 'tax_category'],
      dtype='str'))])