In [7]:
import pandas as pd 

from sklearn.model_selection import train_test_split

from sklearn.linear_model import(
    LinearRegression,
    Lasso,
    Ridge,
    ElasticNet
)

from src.preprocessing import build_preprocessor
from src.train import train_model
from src.evaluate import evaluate_model

In [8]:
df = pd.read_csv("../data/interim/featured_ford.csv")
df.head()

     model  year  price  ... fuel_efficiency  tax_category price_segment
0   Fiesta  2017  12000  ...          medium        medium       Premium
1    Focus  2018  14000  ...          medium        medium       Premium
2    Focus  2017  13000  ...          medium        medium       Premium
3   Fiesta  2019  17500  ...          medium        medium        Luxury
4   Fiesta  2019  16500  ...          medium        medium        Luxury

[5 rows x 15 columns]

In [9]:
X = df.drop("price" , axis= 1)
y = df["price"]

X_train , X_test , y_train , y_test = train_test_split( X , y , test_size=0.2 , random_state= 42)

In [11]:
X

         model  year transmission  ...  fuel_efficiency tax_category  price_segment
0       Fiesta  2017    Automatic  ...           medium       medium        Premium
1        Focus  2018       Manual  ...           medium       medium        Premium
2        Focus  2017       Manual  ...           medium       medium        Premium
3       Fiesta  2019       Manual  ...           medium       medium         Luxury
4       Fiesta  2019    Automatic  ...           medium       medium         Luxury
...        ...   ...          ...  ...              ...          ...            ...
17961    B-MAX  2017       Manual  ...           medium       medium         Budget
17962    B-MAX  2014       Manual  ...           medium          low         Budget
17963    Focus  2015       Manual  ...             high          low        Economy
17964       KA  2018       Manual  ...           medium       medium         Budget
17965    Focus  2015       Manual  ...           medium          low         Budget

[17966 rows x 14 columns]

In [12]:
preprocessor = build_preprocessor(X_train)

In [13]:
linear_pipeline = train_model(
    preprocessor,
    LinearRegression(),
    X_train ,
    y_train
)

In [14]:
linear_metrics = evaluate_model(
    linear_pipeline,
    X_test,
    y_test
)

In [20]:
linear_metrics

{'MAE': 852.4430454815995,
 'MSE': 1618787.4193048694,
 'RMSE': np.float64(1272.31577028066),
 'R2': 0.9277715649409267}

In [23]:
ridge_pipeline = train_model(
    preprocessor,
    Ridge(alpha=1.0),
    X_train,
    y_train
)

ridge_metrics = evaluate_model(
    ridge_pipeline,
    X_test,
    y_test
) 
ridge_metrics

{'MAE': 852.6169442470529,
 'MSE': 1616412.6729463735,
 'RMSE': np.float64(1271.3821899595628),
 'R2': 0.9278775233954408}

In [25]:
lasso_pipeline = train_model(
    preprocessor,
    Lasso(alpha=1.0),
    X_train,
    y_train
)

lasso_metrics = evaluate_model(
    lasso_pipeline,
    X_test,
    y_test
)
lasso_metrics

{'MAE': 854.5182767446114,
 'MSE': 1620695.1956675453,
 'RMSE': np.float64(1273.0652754935802),
 'R2': 0.927686442151192}

In [26]:
elastic_pipeline = train_model(
    preprocessor,
    ElasticNet(alpha= 1.0,
               l1_ratio=0.5),
    X_train,
    y_train
)

elastic_metrics = evaluate_model(
    elastic_pipeline,
    X_test,
    y_test
)

elastic_metrics

{'MAE': 1523.2260690520957,
 'MSE': 4772981.231517318,
 'RMSE': np.float64(2184.7153662473556),
 'R2': 0.7870350604362477}

In [27]:
comparison = pd.DataFrame([
    {
        "Model":"Linear Regression",
        **linear_metrics
    },
    {
        "Model":"Ridge",
        **ridge_metrics
    },
    {
        "Model":"Lasso",
        **lasso_metrics
    },
    {
        "Model":"ElasticNet",
        **elastic_metrics
    }
])

In [28]:
comparison

               Model          MAE           MSE         RMSE        R2
0  Linear Regression   852.443045  1.618787e+06  1272.315770  0.927772
1              Ridge   852.616944  1.616413e+06  1271.382190  0.927878
2              Lasso   854.518277  1.620695e+06  1273.065275  0.927686
3         ElasticNet  1523.226069  4.772981e+06  2184.715366  0.787035

In [29]:
comparison.sort_values(
    by="R2",
    ascending=False
)

               Model          MAE           MSE         RMSE        R2
1              Ridge   852.616944  1.616413e+06  1271.382190  0.927878
0  Linear Regression   852.443045  1.618787e+06  1272.315770  0.927772
2              Lasso   854.518277  1.620695e+06  1273.065275  0.927686
3         ElasticNet  1523.226069  4.772981e+06  2184.715366  0.787035

In [30]:
comparison.sort_values(
    by="RMSE"
)

               Model          MAE           MSE         RMSE        R2
1              Ridge   852.616944  1.616413e+06  1271.382190  0.927878
0  Linear Regression   852.443045  1.618787e+06  1272.315770  0.927772
2              Lasso   854.518277  1.620695e+06  1273.065275  0.927686
3         ElasticNet  1523.226069  4.772981e+06  2184.715366  0.787035